Cl-8-YS read only feature
xDAnkit/code-lele pull request #4
Opened 2024-01-02 12:34 UTC by Yash-Shukla-9

1. Fix: Fixed the navbar which was not showing earlier.
2. Style: Added some padding to the code editor for better viewing.

2024-01-02 12:35 UTC, Yash-Shukla-9 commented
@xDAnkit Sir Please check the PR.

2024-01-03 03:52 UTC, xDAnkit requested changes
@Yash-Shukla-9 - Please review comments

2024-01-03 03:52 UTC, xDAnkit commented on client/src/HomePage.jsx
> +      <Link to={`/${id}`} style={{ textDecoration: "none", color: "black" }}>
@Yash-Shukla-9 - Please remove inline css

2024-01-03 04:32 UTC, Yash-Shukla-9 reviewed
All set to go

2024-01-03 04:33 UTC, xDAnkit requested changes
@Yash-Shukla-9 - Check comments

2024-01-03 04:33 UTC, xDAnkit commented on client/src/HomePage.jsx
> +      <Link to={`/${id}`} className="Button-link">
@Yash-Shukla-9 - Class name should be in correct format `btn-link`

2024-01-03 04:37 UTC, Yash-Shukla-9 reviewed
Fixed the style

2024-01-03 04:37 UTC, xDAnkit approved these changes
Looks good to me

2024-01-03 04:37 UTC, merged