Updated the ReadMe File and fixed the Navigatior bar width
xDAnkit/code-lele pull request #7
Opened 2024-11-18 09:00 UTC by Navdeep-av

Updated the ReadMe File and fixed the Navigatior bar width

2024-11-18 12:00 UTC, xDAnkit requested changes
Pls review comments

2024-11-18 12:00 UTC, xDAnkit commented on client/src/components/organisms/Navbar/NavBar.Component.jsx
> +                textDecoration: "none",
@Navdeep-av - Use styled components

2024-11-18 12:00 UTC, xDAnkit commented on client/src/testing.jsx
> +  console.log("Domain:", import.meta.env.VITE_AUTH_DOMAIN);
@Navdeep-av - Delete this file

2024-11-18 16:47 UTC, Navdeep-av commented
I have made the changes, please review.

2024-11-19 03:28 UTC, xDAnkit requested changes
Pls check it

2024-11-19 03:28 UTC, xDAnkit commented on client/public/css/styles.css
> +.logout-btn{font-weight: 600 !important;}
@Navdeep-av - Remove if not in use

2024-11-19 03:28 UTC, xDAnkit commented on client/public/css/styles.css
> +.nav-width{max-width: 100% !important;}
@Navdeep-av - Format this with prettier

2024-11-19 03:28 UTC, xDAnkit commented on client/public/css/styles.css
> +  /* width: 30px; */
@Navdeep-av - Remove commented code

2024-11-19 03:28 UTC, xDAnkit commented on client/src/main copy.jsx
> +import { createRoot } from "react-dom/client";
@Navdeep-av - Remove unnecessary fille

2024-11-19 03:32 UTC, Navdeep-av commented on client/public/css/styles.css
> +.logout-btn{font-weight: 600 !important;}
@xDAnkit Fixed.

2024-11-19 03:33 UTC, Navdeep-av commented on client/public/css/styles.css
> +  /* width: 30px; */
@xDAnkit Done.

2024-11-19 03:33 UTC, Navdeep-av commented on client/public/css/styles.css
> +.nav-width{max-width: 100% !important;}
@xDAnkit Fixed.

2024-11-19 03:34 UTC, Navdeep-av commented on client/src/main copy.jsx
> +import { createRoot } from "react-dom/client";
@xDAnkit Done

2024-11-19 03:46 UTC, xDAnkit approved these changes
Looks good to me

2024-11-19 03:46 UTC, merged